Repository Prabeshpd/E-Learn, pull requests merged in 2020-11, with the labels that each got.

#5 add actions and reducers
  client/jsconfig.json
  client/src/actions/users.js
  client/src/config.js
  client/src/reducers/users.js
  client/src/services/users.js
  client/src/utils/https.js
  pull_request_template.md
Labels: React, enhancement

#9 Fix typos add missing utils
  client/.eslintrc.json
  client/package.json
  client/src/actions/users.js
  client/src/common/interceptors.js
  client/src/constants/env.js
  client/src/constants/storage.js
  client/src/reducers/auth.js
  client/src/services/tokens.js
  client/src/utils.js/https.js
  client/src/utils/storage.js
  client/yarn.lock
Labels: hotfix

#11 add okta sdk to create user
  server/.env.example
  server/src/config.js
  server/src/controllers/users.js
  server/src/index.js
  server/src/lib/okta.js
  server/src/middlewares/cors.js
  server/src/models/users.js
  server/src/routes/index.js
  server/src/routes/users/index.js
  server/src/services/auth.js
  server/src/services/users.js
Labels: Node, enhancement

#15 Add functionality to create new todo item
  client/package.json
  client/src/assets/plus copy.png
  client/src/components/App.js
  client/src/components/TaskInput/TaskInput.js
  client/src/components/TaskInput/index.js
  client/src/components/TodoList/Todo.js
  client/src/components/TodoList/TodoList.js
  client/src/components/TodoList/index.js
  client/src/components/common/Header.js
  client/src/reducers/todos.js
  client/src/styles/App.css
  client/src/styles/TaskInput.css
  client/yarn.lock
Labels: enhancement

#17 Configure database and server for todo API
  server/.env.example
  server/package-lock.json
  server/src/config.js
  server/src/controllers/todos.js
  server/src/db.js
  server/src/env.js
  server/src/index.js
  server/src/knexfile.js
  server/src/middlewares/cors.js
  server/src/middlewares/errorHandler.js
  server/src/migrations/20201105125515_demo.js
  server/src/models/todos.js
  server/src/models/users.js
  server/src/routes.js
  server/src/routes/index.js
  server/src/routes/todoRoutes.js
  server/src/routes/userRoutes.js
  server/src/seeds/01-users.js
  server/src/seeds/02-todos.js
  server/src/seeds/todo.js
  server/src/services/todos.js
  server/src/stubs/migration.stub
  server/src/stubs/seed.stub
  server/src/utils/buildError.js
  server/yarn.lock
Labels: enhancement

#21 Create action, trigger and resource of todo for zapier integration
  zapier/.env.example
  zapier/.gitignore
  zapier/README.md
  zapier/config.js
  zapier/creates/todo.js
  zapier/env.js
  zapier/index.js
  zapier/package-lock.json
  zapier/package.json
  zapier/resources/todo.js
  zapier/test/creates/todo.js
  zapier/test/resources/todo.js
  zapier/test/triggers/todo.js
  zapier/triggers/todo.js
Labels: Node, enhancement, feature
